config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'profiles/new'
  get 'sessions/new'
  get 'users/new'
  root 'pages#index'
  get 'pages/help'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true,length: {maximum:15}
  
  VALID_EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates :email, presence: true
  
  VALID_PASSWORD_REGEX =/\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,100}+\z/i
  validates :password, presence: true

  has_secure_password
end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  add_flash_types :success, :info, :warning, :danger
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  
  def help 
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def edit
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

 def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_path, success: 'ログインに成功しました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
 end

  private
  def log_in(user)
    session[:user_id] = user.id
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
   #binding.pry
   @user = User.new(user_params)
   if @user.save
     redirect_to root_path, success: 'ユーザーの登録が完了しました'
   else
     flash.now[:danger] = 'ユーザーの登録が失敗しました'
     render :new
   end
  end

 private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kensaku</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>
    
    <%= yield %>
      <script>
      $(function(){
        $(".alert").fadeOut(5000);
      });
    </script>
  </body>
</html>

app/views/pages/help.html.erb
<h1>ヘルプページです</h1>

app/views/pages/index.html.erb
<html>
  <header>
    <h2 class=text-white>建サク.com</h2>
    <div class="header-navigation"></div>
      <%= link_to "新規登録", new_user_path, class: 'btn btn-default' %>
      <%= link_to "ログイン", login_path, class: 'btn btn-default' %>
      <%= link_to "投稿する", root_path, class: 'btn btn-default' %>
    </div>
  </header>
</html>
<body> 
  <div class= "main-visual">
    <div class="main-title">
      <h1 class="text-white">建サク.com</h1>
      <p1 class="text-sub">Everyone who works in the construction industry</p1>
      <p2 class="text-sub">Feel free to connect</p2>
    </div>
  </div>
</body>   

app/views/password_resets/edit.html.erb
<h1>PasswordResets#edit</h1>
<p>Find me in app/views/password_resets/edit.html.erb</p>

app/views/password_resets/new.html.erb
<div class="sub-visual">
  <div class="container">
    <h1 class="text-title2">パスワード再設定</h1>
    <%= form_for :password_reset, url: password_resets_path do |f| %>
      <div class="form-group">
        <%= f.label :email_address, 'メールアドレス' %>
        <%= f.text_field :email, class: 'form-control' %>
      </div>
      <%= f.submit '送信する', class: 'btn2' %>
    <% end %>
  </div>
</div>

app/views/profiles/new.html.erb
      <%= f.label :first_name, '性' %>
      <%= f.text_field :name, class: 'form-control' %>
    
      <%= f.label :last_name, '名' %>
      <%= f.text_field :name, class: 'form-control' %>
    
      <%= f.label :email_address, 'メールアドレス' %>
      <%= f.text_field :email, class: 'form-control' %>
    
      <%= f.label :password, 'パスワード （半角6文字以上で英数字1文字以上含む必要があります。） '%>
      <%= f.password_field :password, class: 'form-control' %>
    
      <%= f.label :password_confirmation, 'パスワード確認' %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      
    <%= f.submit '登録する', class: 'btn2' %>
    



<h1>Profiles#new</h1>
<p>Find me in app/views/profiles/new.html.erb</p>

app/views/users/new.html.erb
<div class="users-visual">
  <h1 class="text-title">新規登録</h1>
  <%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :first_name, '性' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :last_name, '名' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :email_address, 'メールアドレス' %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password, 'パスワード （半角6文字以上で英数字1文字以上含む必要があります。） '%>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, 'パスワード確認' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
  <%= f.submit '登録する', class: 'btn2' %>
  <% end %>
  <div class="container">
    <p3 class="text-sub2">すでにアカウントをお持ちですか？</p3> 
    <%= link_to 'ログインはこちら', login_path, class: 'text-white' %>
  </div>
</div>